### ISSUE TITLE
wacopymate not working anymore 

### ISSUE THREAD

**Issue by mahdialajmy** [Suleman-Elahi/WACopyMate#1]
hello .. please check and update the wacopymate extension for chrome and edge 
it was a great tool and  not working anymore after the latest browser updates

**Comment by Suleman-Elahi** [comment]
will look into it and report back

**Comment by Suleman-Elahi** [comment]
Fixed: https://github.com/Suleman-Elahi/WACopyMate/commit/7c508ec8fb87e56c30bd67e53e8d864d85464dd0

The store links will take time. Meanwhile, you can install the Chrome/Edge extension from source here. And thank you for reporting.
